Update 7/23/2019

diff --git a/scripts/git-scripts/git-backup b/scripts/git-scripts/git-backup
--- a/scripts/git-scripts/git-backup
+++ b/scripts/git-scripts/git-backup
@@ -1,6 +1,15 @@
 #!/bin/bash
-set -ex
+set -eo pipefail
 
 CUR_BRANCH=`git rev-parse --abbrev-ref HEAD`
 NEW_BRANCH="${CUR_BRANCH}_backup-$(date +%Y.%m.%d-%H.%M)"
-git branch "$NEW_BRANCH"
+
+if [ "$1" == "--create" ] || [ "$1" = "-c" ]; then
+  git branch "$NEW_BRANCH"
+  echo "$NEW_BRANCH"
+elif [ "$1" == "--latest" ] || [ "$1" == "-l" ]; then
+  echo $(git br | grep $(git tb) | grep "_backup-" | sort | tail -1)
+else
+  echo -e "\033[31mInvalid argument. Must provide --create or --latest\033[m"
+  exit 1
+fi
